//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBioSvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carpeta
    {
        public Carpeta()
        {
            this.Archivo = new HashSet<Archivo>();
            this.Carpeta1 = new HashSet<Carpeta>();
            this.Proyecto = new HashSet<Proyecto>();
        }
    
        public System.Guid IdCarpeta { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.Guid> IdCarpetaPadre { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaCreac_on { get; set; }
    
        public virtual ICollection<Archivo> Archivo { get; set; }
        public virtual ICollection<Carpeta> Carpeta1 { get; set; }
        public virtual Carpeta Carpeta2 { get; set; }
        public virtual ICollection<Proyecto> Proyecto { get; set; }
    }
}
