//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBioSvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultado
    {
        public System.Guid IdResultado { get; set; }
        public int NumGenes { get; set; }
        public string NombreGenes { get; set; }
        public string IdGenes { get; set; }
        public double Accuracy_Media { get; set; }
        public double Accuracy_Std { get; set; }
        public double Sensitivity_Media { get; set; }
        public double Sensitivity_Std { get; set; }
        public double Specificity_Media { get; set; }
        public double Specificity_Std { get; set; }
        public Nullable<System.DateTime> FechaLanzamiento { get; set; }
        public Nullable<System.DateTime> FechaFinalizacion { get; set; }
        public Nullable<System.DateTime> Duracion { get; set; }
        public string AccuracyXGenes { get; set; }
        public Nullable<double> Mediana { get; set; }
        public Nullable<System.Guid> IdSimulacion { get; set; }
        public string NombreGenesSolucion { get; set; }
        public string IdGenesSolucion { get; set; }
    
        public virtual Simulacion Simulacion { get; set; }
    }
}
