//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBioSvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Simulacion
    {
        public Simulacion()
        {
            this.Resultado = new HashSet<Resultado>();
        }
    
        public System.Guid IdSimulacion { get; set; }
        public System.Guid IdProyecto { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaCreacionSimulacion { get; set; }
        public System.Guid IdMetodoSeleccion { get; set; }
        public System.Guid IdMetodoClasificacion { get; set; }
        public System.Guid IdEstadoSimulacion { get; set; }
        public string ParametrosSeleccion { get; set; }
        public string ParametrosClasificacion { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.Guid> IdLog { get; set; }
        public System.Guid IdArchivo { get; set; }
        public System.Guid IdCarpeta { get; set; }
    
        public virtual EstadoSimulacion EstadoSimulacion { get; set; }
        public virtual Log Log { get; set; }
        public virtual MetodoClasificacion MetodoClasificacion { get; set; }
        public virtual MetodoSeleccion MetodoSeleccion { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        public virtual ICollection<Resultado> Resultado { get; set; }
    }
}
