#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17626
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace runnerSvc
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="webappDB")]
	public partial class webappDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertArchivo(Archivo instance);
    partial void UpdateArchivo(Archivo instance);
    partial void DeleteArchivo(Archivo instance);
    partial void InsertSimulacion(Simulacion instance);
    partial void UpdateSimulacion(Simulacion instance);
    partial void DeleteSimulacion(Simulacion instance);
    partial void InsertCarpeta(Carpeta instance);
    partial void UpdateCarpeta(Carpeta instance);
    partial void DeleteCarpeta(Carpeta instance);
    partial void InsertEstadoSimulacion(EstadoSimulacion instance);
    partial void UpdateEstadoSimulacion(EstadoSimulacion instance);
    partial void DeleteEstadoSimulacion(EstadoSimulacion instance);
    partial void InsertMetodoClasificacion(MetodoClasificacion instance);
    partial void UpdateMetodoClasificacion(MetodoClasificacion instance);
    partial void DeleteMetodoClasificacion(MetodoClasificacion instance);
    partial void InsertMetodoSeleccion(MetodoSeleccion instance);
    partial void UpdateMetodoSeleccion(MetodoSeleccion instance);
    partial void DeleteMetodoSeleccion(MetodoSeleccion instance);
    partial void InsertProyecto(Proyecto instance);
    partial void UpdateProyecto(Proyecto instance);
    partial void DeleteProyecto(Proyecto instance);
    partial void InsertResultados(Resultados instance);
    partial void UpdateResultados(Resultados instance);
    partial void DeleteResultados(Resultados instance);
    #endregion
		
		public webappDBDataContext() : 
				base(global::runnerSvc.Properties.Settings.Default.webappDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public webappDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public webappDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public webappDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public webappDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Archivo> Archivo
		{
			get
			{
				return this.GetTable<Archivo>();
			}
		}
		
		public System.Data.Linq.Table<Simulacion> Simulacion
		{
			get
			{
				return this.GetTable<Simulacion>();
			}
		}
		
		public System.Data.Linq.Table<Carpeta> Carpeta
		{
			get
			{
				return this.GetTable<Carpeta>();
			}
		}
		
		public System.Data.Linq.Table<EstadoSimulacion> EstadoSimulacion
		{
			get
			{
				return this.GetTable<EstadoSimulacion>();
			}
		}
		
		public System.Data.Linq.Table<MetodoClasificacion> MetodoClasificacion
		{
			get
			{
				return this.GetTable<MetodoClasificacion>();
			}
		}
		
		public System.Data.Linq.Table<MetodoSeleccion> MetodoSeleccion
		{
			get
			{
				return this.GetTable<MetodoSeleccion>();
			}
		}
		
		public System.Data.Linq.Table<Proyecto> Proyecto
		{
			get
			{
				return this.GetTable<Proyecto>();
			}
		}
		
		public System.Data.Linq.Table<Resultados> Resultados
		{
			get
			{
				return this.GetTable<Resultados>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Archivo")]
	public partial class Archivo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _idArchivo;
		
		private System.Guid _idCarpeta;
		
		private string _usuario;
		
		private bool _publico;
		
		private string _nombre;
		
		private string _content_type;
		
		private System.Data.Linq.Binary _datos;
		
		private System.DateTime _fechaCreacion;
		
		private string _descripcion;
		
		private bool _baseDatos;
		
		private EntitySet<Proyecto> _Proyecto;
		
		private EntityRef<Carpeta> _Carpeta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidArchivoChanging(System.Guid value);
    partial void OnidArchivoChanged();
    partial void OnidCarpetaChanging(System.Guid value);
    partial void OnidCarpetaChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OnpublicoChanging(bool value);
    partial void OnpublicoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Oncontent_typeChanging(string value);
    partial void Oncontent_typeChanged();
    partial void OndatosChanging(System.Data.Linq.Binary value);
    partial void OndatosChanged();
    partial void OnfechaCreacionChanging(System.DateTime value);
    partial void OnfechaCreacionChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnbaseDatosChanging(bool value);
    partial void OnbaseDatosChanged();
    #endregion
		
		public Archivo()
		{
			this._Proyecto = new EntitySet<Proyecto>(new Action<Proyecto>(this.attach_Proyecto), new Action<Proyecto>(this.detach_Proyecto));
			this._Carpeta = default(EntityRef<Carpeta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idArchivo", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid idArchivo
		{
			get
			{
				return this._idArchivo;
			}
			set
			{
				if ((this._idArchivo != value))
				{
					this.OnidArchivoChanging(value);
					this.SendPropertyChanging();
					this._idArchivo = value;
					this.SendPropertyChanged("idArchivo");
					this.OnidArchivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCarpeta", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid idCarpeta
		{
			get
			{
				return this._idCarpeta;
			}
			set
			{
				if ((this._idCarpeta != value))
				{
					if (this._Carpeta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCarpetaChanging(value);
					this.SendPropertyChanging();
					this._idCarpeta = value;
					this.SendPropertyChanged("idCarpeta");
					this.OnidCarpetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publico", DbType="Bit NOT NULL")]
		public bool publico
		{
			get
			{
				return this._publico;
			}
			set
			{
				if ((this._publico != value))
				{
					this.OnpublicoChanging(value);
					this.SendPropertyChanging();
					this._publico = value;
					this.SendPropertyChanged("publico");
					this.OnpublicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[content/type]", Storage="_content_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string content_type
		{
			get
			{
				return this._content_type;
			}
			set
			{
				if ((this._content_type != value))
				{
					this.Oncontent_typeChanging(value);
					this.SendPropertyChanging();
					this._content_type = value;
					this.SendPropertyChanged("content_type");
					this.Oncontent_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datos", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary datos
		{
			get
			{
				return this._datos;
			}
			set
			{
				if ((this._datos != value))
				{
					this.OndatosChanging(value);
					this.SendPropertyChanging();
					this._datos = value;
					this.SendPropertyChanged("datos");
					this.OndatosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime fechaCreacion
		{
			get
			{
				return this._fechaCreacion;
			}
			set
			{
				if ((this._fechaCreacion != value))
				{
					this.OnfechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._fechaCreacion = value;
					this.SendPropertyChanged("fechaCreacion");
					this.OnfechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(500)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_baseDatos", DbType="Bit NOT NULL")]
		public bool baseDatos
		{
			get
			{
				return this._baseDatos;
			}
			set
			{
				if ((this._baseDatos != value))
				{
					this.OnbaseDatosChanging(value);
					this.SendPropertyChanging();
					this._baseDatos = value;
					this.SendPropertyChanged("baseDatos");
					this.OnbaseDatosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Archivo_Proyecto", Storage="_Proyecto", ThisKey="idArchivo", OtherKey="idArchivo")]
		public EntitySet<Proyecto> Proyecto
		{
			get
			{
				return this._Proyecto;
			}
			set
			{
				this._Proyecto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carpeta_Archivo", Storage="_Carpeta", ThisKey="idCarpeta", OtherKey="idCarpeta", IsForeignKey=true)]
		public Carpeta Carpeta
		{
			get
			{
				return this._Carpeta.Entity;
			}
			set
			{
				Carpeta previousValue = this._Carpeta.Entity;
				if (((previousValue != value) 
							|| (this._Carpeta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Carpeta.Entity = null;
						previousValue.Archivo.Remove(this);
					}
					this._Carpeta.Entity = value;
					if ((value != null))
					{
						value.Archivo.Add(this);
						this._idCarpeta = value.idCarpeta;
					}
					else
					{
						this._idCarpeta = default(System.Guid);
					}
					this.SendPropertyChanged("Carpeta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Proyecto(Proyecto entity)
		{
			this.SendPropertyChanging();
			entity.Archivo = this;
		}
		
		private void detach_Proyecto(Proyecto entity)
		{
			this.SendPropertyChanging();
			entity.Archivo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Simulacion")]
	public partial class Simulacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _idSimulacion;
		
		private System.Guid _idProyecto;
		
		private string _nombre;
		
		private string _descripcion;
		
		private System.DateTime _fechaCreacion;
		
		private System.Guid _idMetodoSeleccion;
		
		private System.Guid _idMetodoClasificacion;
		
		private System.Guid _idEstadoSimulacion;
		
		private string _parametrosSeleccion;
		
		private string _parametrosClasificacion;
		
		private string _usuario;
		
		private EntityRef<Resultados> _Resultados;
		
		private EntityRef<EstadoSimulacion> _EstadoSimulacion;
		
		private EntityRef<MetodoClasificacion> _MetodoClasificacion;
		
		private EntityRef<MetodoSeleccion> _MetodoSeleccion;
		
		private EntityRef<Proyecto> _Proyecto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidSimulacionChanging(System.Guid value);
    partial void OnidSimulacionChanged();
    partial void OnidProyectoChanging(System.Guid value);
    partial void OnidProyectoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnfechaCreacionChanging(System.DateTime value);
    partial void OnfechaCreacionChanged();
    partial void OnidMetodoSeleccionChanging(System.Guid value);
    partial void OnidMetodoSeleccionChanged();
    partial void OnidMetodoClasificacionChanging(System.Guid value);
    partial void OnidMetodoClasificacionChanged();
    partial void OnidEstadoSimulacionChanging(System.Guid value);
    partial void OnidEstadoSimulacionChanged();
    partial void OnparametrosSeleccionChanging(string value);
    partial void OnparametrosSeleccionChanged();
    partial void OnparametrosClasificacionChanging(string value);
    partial void OnparametrosClasificacionChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    #endregion
		
		public Simulacion()
		{
			this._Resultados = default(EntityRef<Resultados>);
			this._EstadoSimulacion = default(EntityRef<EstadoSimulacion>);
			this._MetodoClasificacion = default(EntityRef<MetodoClasificacion>);
			this._MetodoSeleccion = default(EntityRef<MetodoSeleccion>);
			this._Proyecto = default(EntityRef<Proyecto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSimulacion", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid idSimulacion
		{
			get
			{
				return this._idSimulacion;
			}
			set
			{
				if ((this._idSimulacion != value))
				{
					this.OnidSimulacionChanging(value);
					this.SendPropertyChanging();
					this._idSimulacion = value;
					this.SendPropertyChanged("idSimulacion");
					this.OnidSimulacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProyecto", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid idProyecto
		{
			get
			{
				return this._idProyecto;
			}
			set
			{
				if ((this._idProyecto != value))
				{
					if (this._Proyecto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidProyectoChanging(value);
					this.SendPropertyChanging();
					this._idProyecto = value;
					this.SendPropertyChanged("idProyecto");
					this.OnidProyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(500)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime fechaCreacion
		{
			get
			{
				return this._fechaCreacion;
			}
			set
			{
				if ((this._fechaCreacion != value))
				{
					this.OnfechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._fechaCreacion = value;
					this.SendPropertyChanged("fechaCreacion");
					this.OnfechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMetodoSeleccion", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid idMetodoSeleccion
		{
			get
			{
				return this._idMetodoSeleccion;
			}
			set
			{
				if ((this._idMetodoSeleccion != value))
				{
					if (this._MetodoSeleccion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidMetodoSeleccionChanging(value);
					this.SendPropertyChanging();
					this._idMetodoSeleccion = value;
					this.SendPropertyChanged("idMetodoSeleccion");
					this.OnidMetodoSeleccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMetodoClasificacion", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid idMetodoClasificacion
		{
			get
			{
				return this._idMetodoClasificacion;
			}
			set
			{
				if ((this._idMetodoClasificacion != value))
				{
					if (this._MetodoClasificacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidMetodoClasificacionChanging(value);
					this.SendPropertyChanging();
					this._idMetodoClasificacion = value;
					this.SendPropertyChanged("idMetodoClasificacion");
					this.OnidMetodoClasificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstadoSimulacion", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid idEstadoSimulacion
		{
			get
			{
				return this._idEstadoSimulacion;
			}
			set
			{
				if ((this._idEstadoSimulacion != value))
				{
					if (this._EstadoSimulacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidEstadoSimulacionChanging(value);
					this.SendPropertyChanging();
					this._idEstadoSimulacion = value;
					this.SendPropertyChanged("idEstadoSimulacion");
					this.OnidEstadoSimulacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parametrosSeleccion", DbType="VarChar(250)")]
		public string parametrosSeleccion
		{
			get
			{
				return this._parametrosSeleccion;
			}
			set
			{
				if ((this._parametrosSeleccion != value))
				{
					this.OnparametrosSeleccionChanging(value);
					this.SendPropertyChanging();
					this._parametrosSeleccion = value;
					this.SendPropertyChanged("parametrosSeleccion");
					this.OnparametrosSeleccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parametrosClasificacion", DbType="VarChar(250)")]
		public string parametrosClasificacion
		{
			get
			{
				return this._parametrosClasificacion;
			}
			set
			{
				if ((this._parametrosClasificacion != value))
				{
					this.OnparametrosClasificacionChanging(value);
					this.SendPropertyChanging();
					this._parametrosClasificacion = value;
					this.SendPropertyChanged("parametrosClasificacion");
					this.OnparametrosClasificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Simulacion_Resultados", Storage="_Resultados", ThisKey="idSimulacion", OtherKey="idResultado", IsUnique=true, IsForeignKey=false)]
		public Resultados Resultados
		{
			get
			{
				return this._Resultados.Entity;
			}
			set
			{
				Resultados previousValue = this._Resultados.Entity;
				if (((previousValue != value) 
							|| (this._Resultados.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Resultados.Entity = null;
						previousValue.Simulacion = null;
					}
					this._Resultados.Entity = value;
					if ((value != null))
					{
						value.Simulacion = this;
					}
					this.SendPropertyChanged("Resultados");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EstadoSimulacion_Simulacion", Storage="_EstadoSimulacion", ThisKey="idEstadoSimulacion", OtherKey="idEstadoSimulacion", IsForeignKey=true)]
		public EstadoSimulacion EstadoSimulacion
		{
			get
			{
				return this._EstadoSimulacion.Entity;
			}
			set
			{
				EstadoSimulacion previousValue = this._EstadoSimulacion.Entity;
				if (((previousValue != value) 
							|| (this._EstadoSimulacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EstadoSimulacion.Entity = null;
						previousValue.Simulacion.Remove(this);
					}
					this._EstadoSimulacion.Entity = value;
					if ((value != null))
					{
						value.Simulacion.Add(this);
						this._idEstadoSimulacion = value.idEstadoSimulacion;
					}
					else
					{
						this._idEstadoSimulacion = default(System.Guid);
					}
					this.SendPropertyChanged("EstadoSimulacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MetodoClasificacion_Simulacion", Storage="_MetodoClasificacion", ThisKey="idMetodoClasificacion", OtherKey="idMetodoClasificacion", IsForeignKey=true)]
		public MetodoClasificacion MetodoClasificacion
		{
			get
			{
				return this._MetodoClasificacion.Entity;
			}
			set
			{
				MetodoClasificacion previousValue = this._MetodoClasificacion.Entity;
				if (((previousValue != value) 
							|| (this._MetodoClasificacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MetodoClasificacion.Entity = null;
						previousValue.Simulacion.Remove(this);
					}
					this._MetodoClasificacion.Entity = value;
					if ((value != null))
					{
						value.Simulacion.Add(this);
						this._idMetodoClasificacion = value.idMetodoClasificacion;
					}
					else
					{
						this._idMetodoClasificacion = default(System.Guid);
					}
					this.SendPropertyChanged("MetodoClasificacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MetodoSeleccion_Simulacion", Storage="_MetodoSeleccion", ThisKey="idMetodoSeleccion", OtherKey="idMetodoSeleccion", IsForeignKey=true)]
		public MetodoSeleccion MetodoSeleccion
		{
			get
			{
				return this._MetodoSeleccion.Entity;
			}
			set
			{
				MetodoSeleccion previousValue = this._MetodoSeleccion.Entity;
				if (((previousValue != value) 
							|| (this._MetodoSeleccion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MetodoSeleccion.Entity = null;
						previousValue.Simulacion.Remove(this);
					}
					this._MetodoSeleccion.Entity = value;
					if ((value != null))
					{
						value.Simulacion.Add(this);
						this._idMetodoSeleccion = value.idMetodoSeleccion;
					}
					else
					{
						this._idMetodoSeleccion = default(System.Guid);
					}
					this.SendPropertyChanged("MetodoSeleccion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proyecto_Simulacion", Storage="_Proyecto", ThisKey="idProyecto", OtherKey="idProyecto", IsForeignKey=true)]
		public Proyecto Proyecto
		{
			get
			{
				return this._Proyecto.Entity;
			}
			set
			{
				Proyecto previousValue = this._Proyecto.Entity;
				if (((previousValue != value) 
							|| (this._Proyecto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Proyecto.Entity = null;
						previousValue.Simulacion.Remove(this);
					}
					this._Proyecto.Entity = value;
					if ((value != null))
					{
						value.Simulacion.Add(this);
						this._idProyecto = value.idProyecto;
					}
					else
					{
						this._idProyecto = default(System.Guid);
					}
					this.SendPropertyChanged("Proyecto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Carpeta")]
	public partial class Carpeta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _idCarpeta;
		
		private string _nombre;
		
		private System.Nullable<System.Guid> _idPadre;
		
		private string _usuario;
		
		private System.DateTime _fechaCreac_on;
		
		private EntitySet<Archivo> _Archivo;
		
		private EntitySet<Carpeta> _Carpeta2;
		
		private EntityRef<Carpeta> _Carpeta1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCarpetaChanging(System.Guid value);
    partial void OnidCarpetaChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnidPadreChanging(System.Nullable<System.Guid> value);
    partial void OnidPadreChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OnfechaCreac_onChanging(System.DateTime value);
    partial void OnfechaCreac_onChanged();
    #endregion
		
		public Carpeta()
		{
			this._Archivo = new EntitySet<Archivo>(new Action<Archivo>(this.attach_Archivo), new Action<Archivo>(this.detach_Archivo));
			this._Carpeta2 = new EntitySet<Carpeta>(new Action<Carpeta>(this.attach_Carpeta2), new Action<Carpeta>(this.detach_Carpeta2));
			this._Carpeta1 = default(EntityRef<Carpeta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCarpeta", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid idCarpeta
		{
			get
			{
				return this._idCarpeta;
			}
			set
			{
				if ((this._idCarpeta != value))
				{
					this.OnidCarpetaChanging(value);
					this.SendPropertyChanging();
					this._idCarpeta = value;
					this.SendPropertyChanged("idCarpeta");
					this.OnidCarpetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPadre", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> idPadre
		{
			get
			{
				return this._idPadre;
			}
			set
			{
				if ((this._idPadre != value))
				{
					if (this._Carpeta1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPadreChanging(value);
					this.SendPropertyChanging();
					this._idPadre = value;
					this.SendPropertyChanged("idPadre");
					this.OnidPadreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[fechaCreac¡on]", Storage="_fechaCreac_on", DbType="DateTime NOT NULL")]
		public System.DateTime fechaCreac_on
		{
			get
			{
				return this._fechaCreac_on;
			}
			set
			{
				if ((this._fechaCreac_on != value))
				{
					this.OnfechaCreac_onChanging(value);
					this.SendPropertyChanging();
					this._fechaCreac_on = value;
					this.SendPropertyChanged("fechaCreac_on");
					this.OnfechaCreac_onChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carpeta_Archivo", Storage="_Archivo", ThisKey="idCarpeta", OtherKey="idCarpeta")]
		public EntitySet<Archivo> Archivo
		{
			get
			{
				return this._Archivo;
			}
			set
			{
				this._Archivo.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carpeta_Carpeta", Storage="_Carpeta2", ThisKey="idCarpeta", OtherKey="idPadre")]
		public EntitySet<Carpeta> Carpeta2
		{
			get
			{
				return this._Carpeta2;
			}
			set
			{
				this._Carpeta2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carpeta_Carpeta", Storage="_Carpeta1", ThisKey="idPadre", OtherKey="idCarpeta", IsForeignKey=true)]
		public Carpeta Carpeta1
		{
			get
			{
				return this._Carpeta1.Entity;
			}
			set
			{
				Carpeta previousValue = this._Carpeta1.Entity;
				if (((previousValue != value) 
							|| (this._Carpeta1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Carpeta1.Entity = null;
						previousValue.Carpeta2.Remove(this);
					}
					this._Carpeta1.Entity = value;
					if ((value != null))
					{
						value.Carpeta2.Add(this);
						this._idPadre = value.idCarpeta;
					}
					else
					{
						this._idPadre = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("Carpeta1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Archivo(Archivo entity)
		{
			this.SendPropertyChanging();
			entity.Carpeta = this;
		}
		
		private void detach_Archivo(Archivo entity)
		{
			this.SendPropertyChanging();
			entity.Carpeta = null;
		}
		
		private void attach_Carpeta2(Carpeta entity)
		{
			this.SendPropertyChanging();
			entity.Carpeta1 = this;
		}
		
		private void detach_Carpeta2(Carpeta entity)
		{
			this.SendPropertyChanging();
			entity.Carpeta1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EstadoSimulacion")]
	public partial class EstadoSimulacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _idEstadoSimulacion;
		
		private string _nombre;
		
		private string _descripcion;
		
		private string _nombreCorto;
		
		private EntitySet<Simulacion> _Simulacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEstadoSimulacionChanging(System.Guid value);
    partial void OnidEstadoSimulacionChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnnombreCortoChanging(string value);
    partial void OnnombreCortoChanged();
    #endregion
		
		public EstadoSimulacion()
		{
			this._Simulacion = new EntitySet<Simulacion>(new Action<Simulacion>(this.attach_Simulacion), new Action<Simulacion>(this.detach_Simulacion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstadoSimulacion", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid idEstadoSimulacion
		{
			get
			{
				return this._idEstadoSimulacion;
			}
			set
			{
				if ((this._idEstadoSimulacion != value))
				{
					this.OnidEstadoSimulacionChanging(value);
					this.SendPropertyChanging();
					this._idEstadoSimulacion = value;
					this.SendPropertyChanged("idEstadoSimulacion");
					this.OnidEstadoSimulacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(250)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreCorto", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string nombreCorto
		{
			get
			{
				return this._nombreCorto;
			}
			set
			{
				if ((this._nombreCorto != value))
				{
					this.OnnombreCortoChanging(value);
					this.SendPropertyChanging();
					this._nombreCorto = value;
					this.SendPropertyChanged("nombreCorto");
					this.OnnombreCortoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EstadoSimulacion_Simulacion", Storage="_Simulacion", ThisKey="idEstadoSimulacion", OtherKey="idEstadoSimulacion")]
		public EntitySet<Simulacion> Simulacion
		{
			get
			{
				return this._Simulacion;
			}
			set
			{
				this._Simulacion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Simulacion(Simulacion entity)
		{
			this.SendPropertyChanging();
			entity.EstadoSimulacion = this;
		}
		
		private void detach_Simulacion(Simulacion entity)
		{
			this.SendPropertyChanging();
			entity.EstadoSimulacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MetodoClasificacion")]
	public partial class MetodoClasificacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _idMetodoClasificacion;
		
		private string _nombre;
		
		private string _descripcion;
		
		private string _parametrosDefecto;
		
		private EntitySet<Simulacion> _Simulacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidMetodoClasificacionChanging(System.Guid value);
    partial void OnidMetodoClasificacionChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnparametrosDefectoChanging(string value);
    partial void OnparametrosDefectoChanged();
    #endregion
		
		public MetodoClasificacion()
		{
			this._Simulacion = new EntitySet<Simulacion>(new Action<Simulacion>(this.attach_Simulacion), new Action<Simulacion>(this.detach_Simulacion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMetodoClasificacion", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid idMetodoClasificacion
		{
			get
			{
				return this._idMetodoClasificacion;
			}
			set
			{
				if ((this._idMetodoClasificacion != value))
				{
					this.OnidMetodoClasificacionChanging(value);
					this.SendPropertyChanging();
					this._idMetodoClasificacion = value;
					this.SendPropertyChanged("idMetodoClasificacion");
					this.OnidMetodoClasificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(500)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parametrosDefecto", DbType="VarChar(250)")]
		public string parametrosDefecto
		{
			get
			{
				return this._parametrosDefecto;
			}
			set
			{
				if ((this._parametrosDefecto != value))
				{
					this.OnparametrosDefectoChanging(value);
					this.SendPropertyChanging();
					this._parametrosDefecto = value;
					this.SendPropertyChanged("parametrosDefecto");
					this.OnparametrosDefectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MetodoClasificacion_Simulacion", Storage="_Simulacion", ThisKey="idMetodoClasificacion", OtherKey="idMetodoClasificacion")]
		public EntitySet<Simulacion> Simulacion
		{
			get
			{
				return this._Simulacion;
			}
			set
			{
				this._Simulacion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Simulacion(Simulacion entity)
		{
			this.SendPropertyChanging();
			entity.MetodoClasificacion = this;
		}
		
		private void detach_Simulacion(Simulacion entity)
		{
			this.SendPropertyChanging();
			entity.MetodoClasificacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MetodoSeleccion")]
	public partial class MetodoSeleccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _idMetodoSeleccion;
		
		private string _nombre;
		
		private string _descripcion;
		
		private string _parametrosDefecto;
		
		private EntitySet<Simulacion> _Simulacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidMetodoSeleccionChanging(System.Guid value);
    partial void OnidMetodoSeleccionChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnparametrosDefectoChanging(string value);
    partial void OnparametrosDefectoChanged();
    #endregion
		
		public MetodoSeleccion()
		{
			this._Simulacion = new EntitySet<Simulacion>(new Action<Simulacion>(this.attach_Simulacion), new Action<Simulacion>(this.detach_Simulacion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMetodoSeleccion", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid idMetodoSeleccion
		{
			get
			{
				return this._idMetodoSeleccion;
			}
			set
			{
				if ((this._idMetodoSeleccion != value))
				{
					this.OnidMetodoSeleccionChanging(value);
					this.SendPropertyChanging();
					this._idMetodoSeleccion = value;
					this.SendPropertyChanged("idMetodoSeleccion");
					this.OnidMetodoSeleccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(500)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parametrosDefecto", DbType="VarChar(250)")]
		public string parametrosDefecto
		{
			get
			{
				return this._parametrosDefecto;
			}
			set
			{
				if ((this._parametrosDefecto != value))
				{
					this.OnparametrosDefectoChanging(value);
					this.SendPropertyChanging();
					this._parametrosDefecto = value;
					this.SendPropertyChanged("parametrosDefecto");
					this.OnparametrosDefectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MetodoSeleccion_Simulacion", Storage="_Simulacion", ThisKey="idMetodoSeleccion", OtherKey="idMetodoSeleccion")]
		public EntitySet<Simulacion> Simulacion
		{
			get
			{
				return this._Simulacion;
			}
			set
			{
				this._Simulacion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Simulacion(Simulacion entity)
		{
			this.SendPropertyChanging();
			entity.MetodoSeleccion = this;
		}
		
		private void detach_Simulacion(Simulacion entity)
		{
			this.SendPropertyChanging();
			entity.MetodoSeleccion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Proyecto")]
	public partial class Proyecto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _idProyecto;
		
		private string _nombre;
		
		private string _descripcion;
		
		private System.Nullable<System.DateTime> _fechaUltimaSimulacion;
		
		private System.DateTime _fechaCreacion;
		
		private System.Guid _idArchivo;
		
		private EntitySet<Simulacion> _Simulacion;
		
		private EntityRef<Archivo> _Archivo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidProyectoChanging(System.Guid value);
    partial void OnidProyectoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnfechaUltimaSimulacionChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaUltimaSimulacionChanged();
    partial void OnfechaCreacionChanging(System.DateTime value);
    partial void OnfechaCreacionChanged();
    partial void OnidArchivoChanging(System.Guid value);
    partial void OnidArchivoChanged();
    #endregion
		
		public Proyecto()
		{
			this._Simulacion = new EntitySet<Simulacion>(new Action<Simulacion>(this.attach_Simulacion), new Action<Simulacion>(this.detach_Simulacion));
			this._Archivo = default(EntityRef<Archivo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProyecto", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid idProyecto
		{
			get
			{
				return this._idProyecto;
			}
			set
			{
				if ((this._idProyecto != value))
				{
					this.OnidProyectoChanging(value);
					this.SendPropertyChanging();
					this._idProyecto = value;
					this.SendPropertyChanged("idProyecto");
					this.OnidProyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(500)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaUltimaSimulacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaUltimaSimulacion
		{
			get
			{
				return this._fechaUltimaSimulacion;
			}
			set
			{
				if ((this._fechaUltimaSimulacion != value))
				{
					this.OnfechaUltimaSimulacionChanging(value);
					this.SendPropertyChanging();
					this._fechaUltimaSimulacion = value;
					this.SendPropertyChanged("fechaUltimaSimulacion");
					this.OnfechaUltimaSimulacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime fechaCreacion
		{
			get
			{
				return this._fechaCreacion;
			}
			set
			{
				if ((this._fechaCreacion != value))
				{
					this.OnfechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._fechaCreacion = value;
					this.SendPropertyChanged("fechaCreacion");
					this.OnfechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idArchivo", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid idArchivo
		{
			get
			{
				return this._idArchivo;
			}
			set
			{
				if ((this._idArchivo != value))
				{
					if (this._Archivo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidArchivoChanging(value);
					this.SendPropertyChanging();
					this._idArchivo = value;
					this.SendPropertyChanged("idArchivo");
					this.OnidArchivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proyecto_Simulacion", Storage="_Simulacion", ThisKey="idProyecto", OtherKey="idProyecto")]
		public EntitySet<Simulacion> Simulacion
		{
			get
			{
				return this._Simulacion;
			}
			set
			{
				this._Simulacion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Archivo_Proyecto", Storage="_Archivo", ThisKey="idArchivo", OtherKey="idArchivo", IsForeignKey=true)]
		public Archivo Archivo
		{
			get
			{
				return this._Archivo.Entity;
			}
			set
			{
				Archivo previousValue = this._Archivo.Entity;
				if (((previousValue != value) 
							|| (this._Archivo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Archivo.Entity = null;
						previousValue.Proyecto.Remove(this);
					}
					this._Archivo.Entity = value;
					if ((value != null))
					{
						value.Proyecto.Add(this);
						this._idArchivo = value.idArchivo;
					}
					else
					{
						this._idArchivo = default(System.Guid);
					}
					this.SendPropertyChanged("Archivo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Simulacion(Simulacion entity)
		{
			this.SendPropertyChanging();
			entity.Proyecto = this;
		}
		
		private void detach_Simulacion(Simulacion entity)
		{
			this.SendPropertyChanging();
			entity.Proyecto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Resultados")]
	public partial class Resultados : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _idResultado;
		
		private int _nGenes;
		
		private System.Data.Linq.Binary _genes;
		
		private double _media;
		
		private double _acierto;
		
		private double _desviacionEstandard;
		
		private double _mediana;
		
		private System.Nullable<System.DateTime> _fechaLanzamiento;
		
		private System.Nullable<System.DateTime> _fechaFinalizacion;
		
		private System.Nullable<System.DateTime> _duracion;
		
		private EntityRef<Simulacion> _Simulacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidResultadoChanging(System.Guid value);
    partial void OnidResultadoChanged();
    partial void OnnGenesChanging(int value);
    partial void OnnGenesChanged();
    partial void OngenesChanging(System.Data.Linq.Binary value);
    partial void OngenesChanged();
    partial void OnmediaChanging(double value);
    partial void OnmediaChanged();
    partial void OnaciertoChanging(double value);
    partial void OnaciertoChanged();
    partial void OndesviacionEstandardChanging(double value);
    partial void OndesviacionEstandardChanged();
    partial void OnmedianaChanging(double value);
    partial void OnmedianaChanged();
    partial void OnfechaLanzamientoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaLanzamientoChanged();
    partial void OnfechaFinalizacionChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaFinalizacionChanged();
    partial void OnduracionChanging(System.Nullable<System.DateTime> value);
    partial void OnduracionChanged();
    #endregion
		
		public Resultados()
		{
			this._Simulacion = default(EntityRef<Simulacion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idResultado", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid idResultado
		{
			get
			{
				return this._idResultado;
			}
			set
			{
				if ((this._idResultado != value))
				{
					if (this._Simulacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidResultadoChanging(value);
					this.SendPropertyChanging();
					this._idResultado = value;
					this.SendPropertyChanged("idResultado");
					this.OnidResultadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nGenes", DbType="Int NOT NULL")]
		public int nGenes
		{
			get
			{
				return this._nGenes;
			}
			set
			{
				if ((this._nGenes != value))
				{
					this.OnnGenesChanging(value);
					this.SendPropertyChanging();
					this._nGenes = value;
					this.SendPropertyChanged("nGenes");
					this.OnnGenesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genes", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary genes
		{
			get
			{
				return this._genes;
			}
			set
			{
				if ((this._genes != value))
				{
					this.OngenesChanging(value);
					this.SendPropertyChanging();
					this._genes = value;
					this.SendPropertyChanged("genes");
					this.OngenesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_media", DbType="Float NOT NULL")]
		public double media
		{
			get
			{
				return this._media;
			}
			set
			{
				if ((this._media != value))
				{
					this.OnmediaChanging(value);
					this.SendPropertyChanging();
					this._media = value;
					this.SendPropertyChanged("media");
					this.OnmediaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acierto", DbType="Float NOT NULL")]
		public double acierto
		{
			get
			{
				return this._acierto;
			}
			set
			{
				if ((this._acierto != value))
				{
					this.OnaciertoChanging(value);
					this.SendPropertyChanging();
					this._acierto = value;
					this.SendPropertyChanged("acierto");
					this.OnaciertoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desviacionEstandard", DbType="Float NOT NULL")]
		public double desviacionEstandard
		{
			get
			{
				return this._desviacionEstandard;
			}
			set
			{
				if ((this._desviacionEstandard != value))
				{
					this.OndesviacionEstandardChanging(value);
					this.SendPropertyChanging();
					this._desviacionEstandard = value;
					this.SendPropertyChanged("desviacionEstandard");
					this.OndesviacionEstandardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mediana", DbType="Float NOT NULL")]
		public double mediana
		{
			get
			{
				return this._mediana;
			}
			set
			{
				if ((this._mediana != value))
				{
					this.OnmedianaChanging(value);
					this.SendPropertyChanging();
					this._mediana = value;
					this.SendPropertyChanged("mediana");
					this.OnmedianaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaLanzamiento", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaLanzamiento
		{
			get
			{
				return this._fechaLanzamiento;
			}
			set
			{
				if ((this._fechaLanzamiento != value))
				{
					this.OnfechaLanzamientoChanging(value);
					this.SendPropertyChanging();
					this._fechaLanzamiento = value;
					this.SendPropertyChanged("fechaLanzamiento");
					this.OnfechaLanzamientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaFinalizacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaFinalizacion
		{
			get
			{
				return this._fechaFinalizacion;
			}
			set
			{
				if ((this._fechaFinalizacion != value))
				{
					this.OnfechaFinalizacionChanging(value);
					this.SendPropertyChanging();
					this._fechaFinalizacion = value;
					this.SendPropertyChanged("fechaFinalizacion");
					this.OnfechaFinalizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duracion", DbType="DateTime")]
		public System.Nullable<System.DateTime> duracion
		{
			get
			{
				return this._duracion;
			}
			set
			{
				if ((this._duracion != value))
				{
					this.OnduracionChanging(value);
					this.SendPropertyChanging();
					this._duracion = value;
					this.SendPropertyChanged("duracion");
					this.OnduracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Simulacion_Resultados", Storage="_Simulacion", ThisKey="idResultado", OtherKey="idSimulacion", IsForeignKey=true)]
		public Simulacion Simulacion
		{
			get
			{
				return this._Simulacion.Entity;
			}
			set
			{
				Simulacion previousValue = this._Simulacion.Entity;
				if (((previousValue != value) 
							|| (this._Simulacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Simulacion.Entity = null;
						previousValue.Resultados = null;
					}
					this._Simulacion.Entity = value;
					if ((value != null))
					{
						value.Resultados = this;
						this._idResultado = value.idSimulacion;
					}
					else
					{
						this._idResultado = default(System.Guid);
					}
					this.SendPropertyChanged("Simulacion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
