#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace runnerSvc
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="webappDB")]
	public partial class webappDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertArchivo(Archivo instance);
    partial void UpdateArchivo(Archivo instance);
    partial void DeleteArchivo(Archivo instance);
    partial void InsertSimulacion(Simulacion instance);
    partial void UpdateSimulacion(Simulacion instance);
    partial void DeleteSimulacion(Simulacion instance);
    partial void InsertCarpeta(Carpeta instance);
    partial void UpdateCarpeta(Carpeta instance);
    partial void DeleteCarpeta(Carpeta instance);
    partial void InsertEstadoSimulacion(EstadoSimulacion instance);
    partial void UpdateEstadoSimulacion(EstadoSimulacion instance);
    partial void DeleteEstadoSimulacion(EstadoSimulacion instance);
    partial void InsertLog(Log instance);
    partial void UpdateLog(Log instance);
    partial void DeleteLog(Log instance);
    partial void InsertMetodoClasificacion(MetodoClasificacion instance);
    partial void UpdateMetodoClasificacion(MetodoClasificacion instance);
    partial void DeleteMetodoClasificacion(MetodoClasificacion instance);
    partial void InsertMetodoSeleccion(MetodoSeleccion instance);
    partial void UpdateMetodoSeleccion(MetodoSeleccion instance);
    partial void DeleteMetodoSeleccion(MetodoSeleccion instance);
    partial void InsertProyecto(Proyecto instance);
    partial void UpdateProyecto(Proyecto instance);
    partial void DeleteProyecto(Proyecto instance);
    partial void InsertResultados(Resultados instance);
    partial void UpdateResultados(Resultados instance);
    partial void DeleteResultados(Resultados instance);
    #endregion
		
		public webappDBDataContext() : 
				base(global::runnerSvc.Properties.Settings.Default.webappDBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public webappDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public webappDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public webappDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public webappDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Archivo> Archivo
		{
			get
			{
				return this.GetTable<Archivo>();
			}
		}
		
		public System.Data.Linq.Table<Simulacion> Simulacion
		{
			get
			{
				return this.GetTable<Simulacion>();
			}
		}
		
		public System.Data.Linq.Table<Carpeta> Carpeta
		{
			get
			{
				return this.GetTable<Carpeta>();
			}
		}
		
		public System.Data.Linq.Table<EstadoSimulacion> EstadoSimulacion
		{
			get
			{
				return this.GetTable<EstadoSimulacion>();
			}
		}
		
		public System.Data.Linq.Table<Log> Log
		{
			get
			{
				return this.GetTable<Log>();
			}
		}
		
		public System.Data.Linq.Table<MetodoClasificacion> MetodoClasificacion
		{
			get
			{
				return this.GetTable<MetodoClasificacion>();
			}
		}
		
		public System.Data.Linq.Table<MetodoSeleccion> MetodoSeleccion
		{
			get
			{
				return this.GetTable<MetodoSeleccion>();
			}
		}
		
		public System.Data.Linq.Table<Proyecto> Proyecto
		{
			get
			{
				return this.GetTable<Proyecto>();
			}
		}
		
		public System.Data.Linq.Table<Resultados> Resultados
		{
			get
			{
				return this.GetTable<Resultados>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Archivo")]
	public partial class Archivo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _IdArchivo;
		
		private System.Guid _IdCarpeta;
		
		private string _Usuario;
		
		private bool _Publico;
		
		private string _NombreArchivo;
		
		private string _ContentType;
		
		private System.DateTime _FechaCreacion;
		
		private string _Descripcion;
		
		private bool _BaseDatos;
		
		private System.Data.Linq.Binary _Datos;
		
		private EntitySet<Proyecto> _Proyecto;
		
		private EntityRef<Carpeta> _Carpeta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdArchivoChanging(System.Guid value);
    partial void OnIdArchivoChanged();
    partial void OnIdCarpetaChanging(System.Guid value);
    partial void OnIdCarpetaChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnPublicoChanging(bool value);
    partial void OnPublicoChanged();
    partial void OnNombreArchivoChanging(string value);
    partial void OnNombreArchivoChanged();
    partial void OnContentTypeChanging(string value);
    partial void OnContentTypeChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnBaseDatosChanging(bool value);
    partial void OnBaseDatosChanged();
    partial void OnDatosChanging(System.Data.Linq.Binary value);
    partial void OnDatosChanged();
    #endregion
		
		public Archivo()
		{
			this._Proyecto = new EntitySet<Proyecto>(new Action<Proyecto>(this.attach_Proyecto), new Action<Proyecto>(this.detach_Proyecto));
			this._Carpeta = default(EntityRef<Carpeta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArchivo", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid IdArchivo
		{
			get
			{
				return this._IdArchivo;
			}
			set
			{
				if ((this._IdArchivo != value))
				{
					this.OnIdArchivoChanging(value);
					this.SendPropertyChanging();
					this._IdArchivo = value;
					this.SendPropertyChanged("IdArchivo");
					this.OnIdArchivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCarpeta", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid IdCarpeta
		{
			get
			{
				return this._IdCarpeta;
			}
			set
			{
				if ((this._IdCarpeta != value))
				{
					if (this._Carpeta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCarpetaChanging(value);
					this.SendPropertyChanging();
					this._IdCarpeta = value;
					this.SendPropertyChanged("IdCarpeta");
					this.OnIdCarpetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Publico", DbType="Bit NOT NULL")]
		public bool Publico
		{
			get
			{
				return this._Publico;
			}
			set
			{
				if ((this._Publico != value))
				{
					this.OnPublicoChanging(value);
					this.SendPropertyChanging();
					this._Publico = value;
					this.SendPropertyChanged("Publico");
					this.OnPublicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreArchivo", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string NombreArchivo
		{
			get
			{
				return this._NombreArchivo;
			}
			set
			{
				if ((this._NombreArchivo != value))
				{
					this.OnNombreArchivoChanging(value);
					this.SendPropertyChanging();
					this._NombreArchivo = value;
					this.SendPropertyChanged("NombreArchivo");
					this.OnNombreArchivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContentType", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ContentType
		{
			get
			{
				return this._ContentType;
			}
			set
			{
				if ((this._ContentType != value))
				{
					this.OnContentTypeChanging(value);
					this.SendPropertyChanging();
					this._ContentType = value;
					this.SendPropertyChanged("ContentType");
					this.OnContentTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseDatos", DbType="Bit NOT NULL")]
		public bool BaseDatos
		{
			get
			{
				return this._BaseDatos;
			}
			set
			{
				if ((this._BaseDatos != value))
				{
					this.OnBaseDatosChanging(value);
					this.SendPropertyChanging();
					this._BaseDatos = value;
					this.SendPropertyChanged("BaseDatos");
					this.OnBaseDatosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datos", DbType="Binary(50)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Datos
		{
			get
			{
				return this._Datos;
			}
			set
			{
				if ((this._Datos != value))
				{
					this.OnDatosChanging(value);
					this.SendPropertyChanging();
					this._Datos = value;
					this.SendPropertyChanged("Datos");
					this.OnDatosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Archivo_Proyecto", Storage="_Proyecto", ThisKey="IdArchivo", OtherKey="idArchivo")]
		public EntitySet<Proyecto> Proyecto
		{
			get
			{
				return this._Proyecto;
			}
			set
			{
				this._Proyecto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carpeta_Archivo", Storage="_Carpeta", ThisKey="IdCarpeta", OtherKey="IdCarpeta", IsForeignKey=true)]
		public Carpeta Carpeta
		{
			get
			{
				return this._Carpeta.Entity;
			}
			set
			{
				Carpeta previousValue = this._Carpeta.Entity;
				if (((previousValue != value) 
							|| (this._Carpeta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Carpeta.Entity = null;
						previousValue.Archivo.Remove(this);
					}
					this._Carpeta.Entity = value;
					if ((value != null))
					{
						value.Archivo.Add(this);
						this._IdCarpeta = value.IdCarpeta;
					}
					else
					{
						this._IdCarpeta = default(System.Guid);
					}
					this.SendPropertyChanged("Carpeta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Proyecto(Proyecto entity)
		{
			this.SendPropertyChanging();
			entity.Archivo = this;
		}
		
		private void detach_Proyecto(Proyecto entity)
		{
			this.SendPropertyChanging();
			entity.Archivo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Simulacion")]
	public partial class Simulacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _idSimulacion;
		
		private System.Guid _idProyecto;
		
		private string _nombre;
		
		private string _descripcion;
		
		private System.DateTime _fechaCreacion;
		
		private System.Guid _idMetodoSeleccion;
		
		private System.Guid _idMetodoClasificacion;
		
		private System.Guid _idEstadoSimulacion;
		
		private string _parametrosSeleccion;
		
		private string _parametrosClasificacion;
		
		private string _usuario;
		
		private EntitySet<Log> _Log;
		
		private EntityRef<Resultados> _Resultados;
		
		private EntityRef<EstadoSimulacion> _EstadoSimulacion;
		
		private EntityRef<MetodoClasificacion> _MetodoClasificacion;
		
		private EntityRef<MetodoSeleccion> _MetodoSeleccion;
		
		private EntityRef<Proyecto> _Proyecto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidSimulacionChanging(System.Guid value);
    partial void OnidSimulacionChanged();
    partial void OnidProyectoChanging(System.Guid value);
    partial void OnidProyectoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnfechaCreacionChanging(System.DateTime value);
    partial void OnfechaCreacionChanged();
    partial void OnidMetodoSeleccionChanging(System.Guid value);
    partial void OnidMetodoSeleccionChanged();
    partial void OnidMetodoClasificacionChanging(System.Guid value);
    partial void OnidMetodoClasificacionChanged();
    partial void OnidEstadoSimulacionChanging(System.Guid value);
    partial void OnidEstadoSimulacionChanged();
    partial void OnparametrosSeleccionChanging(string value);
    partial void OnparametrosSeleccionChanged();
    partial void OnparametrosClasificacionChanging(string value);
    partial void OnparametrosClasificacionChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    #endregion
		
		public Simulacion()
		{
			this._Log = new EntitySet<Log>(new Action<Log>(this.attach_Log), new Action<Log>(this.detach_Log));
			this._Resultados = default(EntityRef<Resultados>);
			this._EstadoSimulacion = default(EntityRef<EstadoSimulacion>);
			this._MetodoClasificacion = default(EntityRef<MetodoClasificacion>);
			this._MetodoSeleccion = default(EntityRef<MetodoSeleccion>);
			this._Proyecto = default(EntityRef<Proyecto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSimulacion", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid idSimulacion
		{
			get
			{
				return this._idSimulacion;
			}
			set
			{
				if ((this._idSimulacion != value))
				{
					this.OnidSimulacionChanging(value);
					this.SendPropertyChanging();
					this._idSimulacion = value;
					this.SendPropertyChanged("idSimulacion");
					this.OnidSimulacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProyecto", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid idProyecto
		{
			get
			{
				return this._idProyecto;
			}
			set
			{
				if ((this._idProyecto != value))
				{
					if (this._Proyecto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidProyectoChanging(value);
					this.SendPropertyChanging();
					this._idProyecto = value;
					this.SendPropertyChanged("idProyecto");
					this.OnidProyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(500)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime fechaCreacion
		{
			get
			{
				return this._fechaCreacion;
			}
			set
			{
				if ((this._fechaCreacion != value))
				{
					this.OnfechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._fechaCreacion = value;
					this.SendPropertyChanged("fechaCreacion");
					this.OnfechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMetodoSeleccion", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid idMetodoSeleccion
		{
			get
			{
				return this._idMetodoSeleccion;
			}
			set
			{
				if ((this._idMetodoSeleccion != value))
				{
					if (this._MetodoSeleccion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidMetodoSeleccionChanging(value);
					this.SendPropertyChanging();
					this._idMetodoSeleccion = value;
					this.SendPropertyChanged("idMetodoSeleccion");
					this.OnidMetodoSeleccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMetodoClasificacion", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid idMetodoClasificacion
		{
			get
			{
				return this._idMetodoClasificacion;
			}
			set
			{
				if ((this._idMetodoClasificacion != value))
				{
					if (this._MetodoClasificacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidMetodoClasificacionChanging(value);
					this.SendPropertyChanging();
					this._idMetodoClasificacion = value;
					this.SendPropertyChanged("idMetodoClasificacion");
					this.OnidMetodoClasificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstadoSimulacion", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid idEstadoSimulacion
		{
			get
			{
				return this._idEstadoSimulacion;
			}
			set
			{
				if ((this._idEstadoSimulacion != value))
				{
					if (this._EstadoSimulacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidEstadoSimulacionChanging(value);
					this.SendPropertyChanging();
					this._idEstadoSimulacion = value;
					this.SendPropertyChanged("idEstadoSimulacion");
					this.OnidEstadoSimulacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parametrosSeleccion", DbType="VarChar(250)")]
		public string parametrosSeleccion
		{
			get
			{
				return this._parametrosSeleccion;
			}
			set
			{
				if ((this._parametrosSeleccion != value))
				{
					this.OnparametrosSeleccionChanging(value);
					this.SendPropertyChanging();
					this._parametrosSeleccion = value;
					this.SendPropertyChanged("parametrosSeleccion");
					this.OnparametrosSeleccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parametrosClasificacion", DbType="VarChar(250)")]
		public string parametrosClasificacion
		{
			get
			{
				return this._parametrosClasificacion;
			}
			set
			{
				if ((this._parametrosClasificacion != value))
				{
					this.OnparametrosClasificacionChanging(value);
					this.SendPropertyChanging();
					this._parametrosClasificacion = value;
					this.SendPropertyChanged("parametrosClasificacion");
					this.OnparametrosClasificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Simulacion_Log", Storage="_Log", ThisKey="idSimulacion", OtherKey="IdSimulacion")]
		public EntitySet<Log> Log
		{
			get
			{
				return this._Log;
			}
			set
			{
				this._Log.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Simulacion_Resultados", Storage="_Resultados", ThisKey="idSimulacion", OtherKey="IdResultado", IsUnique=true, IsForeignKey=false)]
		public Resultados Resultados
		{
			get
			{
				return this._Resultados.Entity;
			}
			set
			{
				Resultados previousValue = this._Resultados.Entity;
				if (((previousValue != value) 
							|| (this._Resultados.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Resultados.Entity = null;
						previousValue.Simulacion = null;
					}
					this._Resultados.Entity = value;
					if ((value != null))
					{
						value.Simulacion = this;
					}
					this.SendPropertyChanged("Resultados");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EstadoSimulacion_Simulacion", Storage="_EstadoSimulacion", ThisKey="idEstadoSimulacion", OtherKey="idEstadoSimulacion", IsForeignKey=true)]
		public EstadoSimulacion EstadoSimulacion
		{
			get
			{
				return this._EstadoSimulacion.Entity;
			}
			set
			{
				EstadoSimulacion previousValue = this._EstadoSimulacion.Entity;
				if (((previousValue != value) 
							|| (this._EstadoSimulacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EstadoSimulacion.Entity = null;
						previousValue.Simulacion.Remove(this);
					}
					this._EstadoSimulacion.Entity = value;
					if ((value != null))
					{
						value.Simulacion.Add(this);
						this._idEstadoSimulacion = value.idEstadoSimulacion;
					}
					else
					{
						this._idEstadoSimulacion = default(System.Guid);
					}
					this.SendPropertyChanged("EstadoSimulacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MetodoClasificacion_Simulacion", Storage="_MetodoClasificacion", ThisKey="idMetodoClasificacion", OtherKey="IdMetodoClasificacion", IsForeignKey=true)]
		public MetodoClasificacion MetodoClasificacion
		{
			get
			{
				return this._MetodoClasificacion.Entity;
			}
			set
			{
				MetodoClasificacion previousValue = this._MetodoClasificacion.Entity;
				if (((previousValue != value) 
							|| (this._MetodoClasificacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MetodoClasificacion.Entity = null;
						previousValue.Simulacion.Remove(this);
					}
					this._MetodoClasificacion.Entity = value;
					if ((value != null))
					{
						value.Simulacion.Add(this);
						this._idMetodoClasificacion = value.IdMetodoClasificacion;
					}
					else
					{
						this._idMetodoClasificacion = default(System.Guid);
					}
					this.SendPropertyChanged("MetodoClasificacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MetodoSeleccion_Simulacion", Storage="_MetodoSeleccion", ThisKey="idMetodoSeleccion", OtherKey="IdMetodoSeleccion", IsForeignKey=true)]
		public MetodoSeleccion MetodoSeleccion
		{
			get
			{
				return this._MetodoSeleccion.Entity;
			}
			set
			{
				MetodoSeleccion previousValue = this._MetodoSeleccion.Entity;
				if (((previousValue != value) 
							|| (this._MetodoSeleccion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MetodoSeleccion.Entity = null;
						previousValue.Simulacion.Remove(this);
					}
					this._MetodoSeleccion.Entity = value;
					if ((value != null))
					{
						value.Simulacion.Add(this);
						this._idMetodoSeleccion = value.IdMetodoSeleccion;
					}
					else
					{
						this._idMetodoSeleccion = default(System.Guid);
					}
					this.SendPropertyChanged("MetodoSeleccion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proyecto_Simulacion", Storage="_Proyecto", ThisKey="idProyecto", OtherKey="idProyecto", IsForeignKey=true)]
		public Proyecto Proyecto
		{
			get
			{
				return this._Proyecto.Entity;
			}
			set
			{
				Proyecto previousValue = this._Proyecto.Entity;
				if (((previousValue != value) 
							|| (this._Proyecto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Proyecto.Entity = null;
						previousValue.Simulacion.Remove(this);
					}
					this._Proyecto.Entity = value;
					if ((value != null))
					{
						value.Simulacion.Add(this);
						this._idProyecto = value.idProyecto;
					}
					else
					{
						this._idProyecto = default(System.Guid);
					}
					this.SendPropertyChanged("Proyecto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Log(Log entity)
		{
			this.SendPropertyChanging();
			entity.Simulacion = this;
		}
		
		private void detach_Log(Log entity)
		{
			this.SendPropertyChanging();
			entity.Simulacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Carpeta")]
	public partial class Carpeta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _IdCarpeta;
		
		private string _Nombre;
		
		private System.Nullable<System.Guid> _IdCarpetaPadre;
		
		private string _Usuario;
		
		private System.DateTime _FechaCreac_on;
		
		private EntitySet<Archivo> _Archivo;
		
		private EntitySet<Carpeta> _Carpeta2;
		
		private EntityRef<Carpeta> _Carpeta1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCarpetaChanging(System.Guid value);
    partial void OnIdCarpetaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnIdCarpetaPadreChanging(System.Nullable<System.Guid> value);
    partial void OnIdCarpetaPadreChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnFechaCreac_onChanging(System.DateTime value);
    partial void OnFechaCreac_onChanged();
    #endregion
		
		public Carpeta()
		{
			this._Archivo = new EntitySet<Archivo>(new Action<Archivo>(this.attach_Archivo), new Action<Archivo>(this.detach_Archivo));
			this._Carpeta2 = new EntitySet<Carpeta>(new Action<Carpeta>(this.attach_Carpeta2), new Action<Carpeta>(this.detach_Carpeta2));
			this._Carpeta1 = default(EntityRef<Carpeta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCarpeta", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid IdCarpeta
		{
			get
			{
				return this._IdCarpeta;
			}
			set
			{
				if ((this._IdCarpeta != value))
				{
					this.OnIdCarpetaChanging(value);
					this.SendPropertyChanging();
					this._IdCarpeta = value;
					this.SendPropertyChanged("IdCarpeta");
					this.OnIdCarpetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCarpetaPadre", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> IdCarpetaPadre
		{
			get
			{
				return this._IdCarpetaPadre;
			}
			set
			{
				if ((this._IdCarpetaPadre != value))
				{
					if (this._Carpeta1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCarpetaPadreChanging(value);
					this.SendPropertyChanging();
					this._IdCarpetaPadre = value;
					this.SendPropertyChanged("IdCarpetaPadre");
					this.OnIdCarpetaPadreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[FechaCreac¡on]", Storage="_FechaCreac_on", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreac_on
		{
			get
			{
				return this._FechaCreac_on;
			}
			set
			{
				if ((this._FechaCreac_on != value))
				{
					this.OnFechaCreac_onChanging(value);
					this.SendPropertyChanging();
					this._FechaCreac_on = value;
					this.SendPropertyChanged("FechaCreac_on");
					this.OnFechaCreac_onChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carpeta_Archivo", Storage="_Archivo", ThisKey="IdCarpeta", OtherKey="IdCarpeta")]
		public EntitySet<Archivo> Archivo
		{
			get
			{
				return this._Archivo;
			}
			set
			{
				this._Archivo.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carpeta_Carpeta", Storage="_Carpeta2", ThisKey="IdCarpeta", OtherKey="IdCarpetaPadre")]
		public EntitySet<Carpeta> Carpeta2
		{
			get
			{
				return this._Carpeta2;
			}
			set
			{
				this._Carpeta2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carpeta_Carpeta", Storage="_Carpeta1", ThisKey="IdCarpetaPadre", OtherKey="IdCarpeta", IsForeignKey=true)]
		public Carpeta Carpeta1
		{
			get
			{
				return this._Carpeta1.Entity;
			}
			set
			{
				Carpeta previousValue = this._Carpeta1.Entity;
				if (((previousValue != value) 
							|| (this._Carpeta1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Carpeta1.Entity = null;
						previousValue.Carpeta2.Remove(this);
					}
					this._Carpeta1.Entity = value;
					if ((value != null))
					{
						value.Carpeta2.Add(this);
						this._IdCarpetaPadre = value.IdCarpeta;
					}
					else
					{
						this._IdCarpetaPadre = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("Carpeta1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Archivo(Archivo entity)
		{
			this.SendPropertyChanging();
			entity.Carpeta = this;
		}
		
		private void detach_Archivo(Archivo entity)
		{
			this.SendPropertyChanging();
			entity.Carpeta = null;
		}
		
		private void attach_Carpeta2(Carpeta entity)
		{
			this.SendPropertyChanging();
			entity.Carpeta1 = this;
		}
		
		private void detach_Carpeta2(Carpeta entity)
		{
			this.SendPropertyChanging();
			entity.Carpeta1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EstadoSimulacion")]
	public partial class EstadoSimulacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _idEstadoSimulacion;
		
		private string _Nombre;
		
		private string _Sescripcion;
		
		private string _NombreCorto;
		
		private EntitySet<Simulacion> _Simulacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEstadoSimulacionChanging(System.Guid value);
    partial void OnidEstadoSimulacionChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnSescripcionChanging(string value);
    partial void OnSescripcionChanged();
    partial void OnNombreCortoChanging(string value);
    partial void OnNombreCortoChanged();
    #endregion
		
		public EstadoSimulacion()
		{
			this._Simulacion = new EntitySet<Simulacion>(new Action<Simulacion>(this.attach_Simulacion), new Action<Simulacion>(this.detach_Simulacion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstadoSimulacion", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid idEstadoSimulacion
		{
			get
			{
				return this._idEstadoSimulacion;
			}
			set
			{
				if ((this._idEstadoSimulacion != value))
				{
					this.OnidEstadoSimulacionChanging(value);
					this.SendPropertyChanging();
					this._idEstadoSimulacion = value;
					this.SendPropertyChanged("idEstadoSimulacion");
					this.OnidEstadoSimulacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sescripcion", DbType="VarChar(250)")]
		public string Sescripcion
		{
			get
			{
				return this._Sescripcion;
			}
			set
			{
				if ((this._Sescripcion != value))
				{
					this.OnSescripcionChanging(value);
					this.SendPropertyChanging();
					this._Sescripcion = value;
					this.SendPropertyChanged("Sescripcion");
					this.OnSescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCorto", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string NombreCorto
		{
			get
			{
				return this._NombreCorto;
			}
			set
			{
				if ((this._NombreCorto != value))
				{
					this.OnNombreCortoChanging(value);
					this.SendPropertyChanging();
					this._NombreCorto = value;
					this.SendPropertyChanged("NombreCorto");
					this.OnNombreCortoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EstadoSimulacion_Simulacion", Storage="_Simulacion", ThisKey="idEstadoSimulacion", OtherKey="idEstadoSimulacion")]
		public EntitySet<Simulacion> Simulacion
		{
			get
			{
				return this._Simulacion;
			}
			set
			{
				this._Simulacion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Simulacion(Simulacion entity)
		{
			this.SendPropertyChanging();
			entity.EstadoSimulacion = this;
		}
		
		private void detach_Simulacion(Simulacion entity)
		{
			this.SendPropertyChanging();
			entity.EstadoSimulacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Log]")]
	public partial class Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _IdLog;
		
		private System.Guid _IdSimulacion;
		
		private System.DateTime _FechaLog;
		
		private string _Texto;
		
		private EntityRef<Simulacion> _Simulacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdLogChanging(System.Guid value);
    partial void OnIdLogChanged();
    partial void OnIdSimulacionChanging(System.Guid value);
    partial void OnIdSimulacionChanged();
    partial void OnFechaLogChanging(System.DateTime value);
    partial void OnFechaLogChanged();
    partial void OnTextoChanging(string value);
    partial void OnTextoChanged();
    #endregion
		
		public Log()
		{
			this._Simulacion = default(EntityRef<Simulacion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLog", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid IdLog
		{
			get
			{
				return this._IdLog;
			}
			set
			{
				if ((this._IdLog != value))
				{
					this.OnIdLogChanging(value);
					this.SendPropertyChanging();
					this._IdLog = value;
					this.SendPropertyChanged("IdLog");
					this.OnIdLogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSimulacion", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid IdSimulacion
		{
			get
			{
				return this._IdSimulacion;
			}
			set
			{
				if ((this._IdSimulacion != value))
				{
					if (this._Simulacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdSimulacionChanging(value);
					this.SendPropertyChanging();
					this._IdSimulacion = value;
					this.SendPropertyChanged("IdSimulacion");
					this.OnIdSimulacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaLog", DbType="DateTime NOT NULL")]
		public System.DateTime FechaLog
		{
			get
			{
				return this._FechaLog;
			}
			set
			{
				if ((this._FechaLog != value))
				{
					this.OnFechaLogChanging(value);
					this.SendPropertyChanging();
					this._FechaLog = value;
					this.SendPropertyChanged("FechaLog");
					this.OnFechaLogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Texto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Texto
		{
			get
			{
				return this._Texto;
			}
			set
			{
				if ((this._Texto != value))
				{
					this.OnTextoChanging(value);
					this.SendPropertyChanging();
					this._Texto = value;
					this.SendPropertyChanged("Texto");
					this.OnTextoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Simulacion_Log", Storage="_Simulacion", ThisKey="IdSimulacion", OtherKey="idSimulacion", IsForeignKey=true)]
		public Simulacion Simulacion
		{
			get
			{
				return this._Simulacion.Entity;
			}
			set
			{
				Simulacion previousValue = this._Simulacion.Entity;
				if (((previousValue != value) 
							|| (this._Simulacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Simulacion.Entity = null;
						previousValue.Log.Remove(this);
					}
					this._Simulacion.Entity = value;
					if ((value != null))
					{
						value.Log.Add(this);
						this._IdSimulacion = value.idSimulacion;
					}
					else
					{
						this._IdSimulacion = default(System.Guid);
					}
					this.SendPropertyChanged("Simulacion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MetodoClasificacion")]
	public partial class MetodoClasificacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _IdMetodoClasificacion;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private string _ParametrosDefecto;
		
		private EntitySet<Simulacion> _Simulacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdMetodoClasificacionChanging(System.Guid value);
    partial void OnIdMetodoClasificacionChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnParametrosDefectoChanging(string value);
    partial void OnParametrosDefectoChanged();
    #endregion
		
		public MetodoClasificacion()
		{
			this._Simulacion = new EntitySet<Simulacion>(new Action<Simulacion>(this.attach_Simulacion), new Action<Simulacion>(this.detach_Simulacion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMetodoClasificacion", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid IdMetodoClasificacion
		{
			get
			{
				return this._IdMetodoClasificacion;
			}
			set
			{
				if ((this._IdMetodoClasificacion != value))
				{
					this.OnIdMetodoClasificacionChanging(value);
					this.SendPropertyChanging();
					this._IdMetodoClasificacion = value;
					this.SendPropertyChanged("IdMetodoClasificacion");
					this.OnIdMetodoClasificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParametrosDefecto", DbType="VarChar(250)")]
		public string ParametrosDefecto
		{
			get
			{
				return this._ParametrosDefecto;
			}
			set
			{
				if ((this._ParametrosDefecto != value))
				{
					this.OnParametrosDefectoChanging(value);
					this.SendPropertyChanging();
					this._ParametrosDefecto = value;
					this.SendPropertyChanged("ParametrosDefecto");
					this.OnParametrosDefectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MetodoClasificacion_Simulacion", Storage="_Simulacion", ThisKey="IdMetodoClasificacion", OtherKey="idMetodoClasificacion")]
		public EntitySet<Simulacion> Simulacion
		{
			get
			{
				return this._Simulacion;
			}
			set
			{
				this._Simulacion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Simulacion(Simulacion entity)
		{
			this.SendPropertyChanging();
			entity.MetodoClasificacion = this;
		}
		
		private void detach_Simulacion(Simulacion entity)
		{
			this.SendPropertyChanging();
			entity.MetodoClasificacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MetodoSeleccion")]
	public partial class MetodoSeleccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _IdMetodoSeleccion;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private string _ParametrosDefecto;
		
		private EntitySet<Simulacion> _Simulacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdMetodoSeleccionChanging(System.Guid value);
    partial void OnIdMetodoSeleccionChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnParametrosDefectoChanging(string value);
    partial void OnParametrosDefectoChanged();
    #endregion
		
		public MetodoSeleccion()
		{
			this._Simulacion = new EntitySet<Simulacion>(new Action<Simulacion>(this.attach_Simulacion), new Action<Simulacion>(this.detach_Simulacion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMetodoSeleccion", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid IdMetodoSeleccion
		{
			get
			{
				return this._IdMetodoSeleccion;
			}
			set
			{
				if ((this._IdMetodoSeleccion != value))
				{
					this.OnIdMetodoSeleccionChanging(value);
					this.SendPropertyChanging();
					this._IdMetodoSeleccion = value;
					this.SendPropertyChanged("IdMetodoSeleccion");
					this.OnIdMetodoSeleccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParametrosDefecto", DbType="VarChar(250)")]
		public string ParametrosDefecto
		{
			get
			{
				return this._ParametrosDefecto;
			}
			set
			{
				if ((this._ParametrosDefecto != value))
				{
					this.OnParametrosDefectoChanging(value);
					this.SendPropertyChanging();
					this._ParametrosDefecto = value;
					this.SendPropertyChanged("ParametrosDefecto");
					this.OnParametrosDefectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MetodoSeleccion_Simulacion", Storage="_Simulacion", ThisKey="IdMetodoSeleccion", OtherKey="idMetodoSeleccion")]
		public EntitySet<Simulacion> Simulacion
		{
			get
			{
				return this._Simulacion;
			}
			set
			{
				this._Simulacion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Simulacion(Simulacion entity)
		{
			this.SendPropertyChanging();
			entity.MetodoSeleccion = this;
		}
		
		private void detach_Simulacion(Simulacion entity)
		{
			this.SendPropertyChanging();
			entity.MetodoSeleccion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Proyecto")]
	public partial class Proyecto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _idProyecto;
		
		private string _nombre;
		
		private string _descripcion;
		
		private System.Nullable<System.DateTime> _fechaUltimaSimulacion;
		
		private System.DateTime _fechaCreacion;
		
		private System.Guid _idArchivo;
		
		private EntitySet<Simulacion> _Simulacion;
		
		private EntityRef<Archivo> _Archivo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidProyectoChanging(System.Guid value);
    partial void OnidProyectoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnfechaUltimaSimulacionChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaUltimaSimulacionChanged();
    partial void OnfechaCreacionChanging(System.DateTime value);
    partial void OnfechaCreacionChanged();
    partial void OnidArchivoChanging(System.Guid value);
    partial void OnidArchivoChanged();
    #endregion
		
		public Proyecto()
		{
			this._Simulacion = new EntitySet<Simulacion>(new Action<Simulacion>(this.attach_Simulacion), new Action<Simulacion>(this.detach_Simulacion));
			this._Archivo = default(EntityRef<Archivo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProyecto", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid idProyecto
		{
			get
			{
				return this._idProyecto;
			}
			set
			{
				if ((this._idProyecto != value))
				{
					this.OnidProyectoChanging(value);
					this.SendPropertyChanging();
					this._idProyecto = value;
					this.SendPropertyChanged("idProyecto");
					this.OnidProyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(500)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaUltimaSimulacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaUltimaSimulacion
		{
			get
			{
				return this._fechaUltimaSimulacion;
			}
			set
			{
				if ((this._fechaUltimaSimulacion != value))
				{
					this.OnfechaUltimaSimulacionChanging(value);
					this.SendPropertyChanging();
					this._fechaUltimaSimulacion = value;
					this.SendPropertyChanged("fechaUltimaSimulacion");
					this.OnfechaUltimaSimulacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime fechaCreacion
		{
			get
			{
				return this._fechaCreacion;
			}
			set
			{
				if ((this._fechaCreacion != value))
				{
					this.OnfechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._fechaCreacion = value;
					this.SendPropertyChanged("fechaCreacion");
					this.OnfechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idArchivo", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid idArchivo
		{
			get
			{
				return this._idArchivo;
			}
			set
			{
				if ((this._idArchivo != value))
				{
					if (this._Archivo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidArchivoChanging(value);
					this.SendPropertyChanging();
					this._idArchivo = value;
					this.SendPropertyChanged("idArchivo");
					this.OnidArchivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proyecto_Simulacion", Storage="_Simulacion", ThisKey="idProyecto", OtherKey="idProyecto")]
		public EntitySet<Simulacion> Simulacion
		{
			get
			{
				return this._Simulacion;
			}
			set
			{
				this._Simulacion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Archivo_Proyecto", Storage="_Archivo", ThisKey="idArchivo", OtherKey="IdArchivo", IsForeignKey=true)]
		public Archivo Archivo
		{
			get
			{
				return this._Archivo.Entity;
			}
			set
			{
				Archivo previousValue = this._Archivo.Entity;
				if (((previousValue != value) 
							|| (this._Archivo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Archivo.Entity = null;
						previousValue.Proyecto.Remove(this);
					}
					this._Archivo.Entity = value;
					if ((value != null))
					{
						value.Proyecto.Add(this);
						this._idArchivo = value.IdArchivo;
					}
					else
					{
						this._idArchivo = default(System.Guid);
					}
					this.SendPropertyChanged("Archivo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Simulacion(Simulacion entity)
		{
			this.SendPropertyChanging();
			entity.Proyecto = this;
		}
		
		private void detach_Simulacion(Simulacion entity)
		{
			this.SendPropertyChanging();
			entity.Proyecto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Resultados")]
	public partial class Resultados : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _IdResultado;
		
		private int _Nummgenes;
		
		private string _Nombregenes;
		
		private string _Idgenes;
		
		private double _Accuracy_media;
		
		private double _Accuracy_std;
		
		private double _Precision_media;
		
		private double _Precision_std;
		
		private double _Recall_medio;
		
		private System.Nullable<double> _Recall_std;
		
		private double _AVC_media;
		
		private double _AVC_std;
		
		private System.Nullable<System.DateTime> _FechaLanzamiento;
		
		private System.Nullable<System.DateTime> _FechaFinalizacion;
		
		private System.Nullable<System.DateTime> _Duracion;
		
		private string _Accuracyxgenes;
		
		private double _Mediana;
		
		private EntityRef<Simulacion> _Simulacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdResultadoChanging(System.Guid value);
    partial void OnIdResultadoChanged();
    partial void OnNummgenesChanging(int value);
    partial void OnNummgenesChanged();
    partial void OnNombregenesChanging(string value);
    partial void OnNombregenesChanged();
    partial void OnIdgenesChanging(string value);
    partial void OnIdgenesChanged();
    partial void OnAccuracy_mediaChanging(double value);
    partial void OnAccuracy_mediaChanged();
    partial void OnAccuracy_stdChanging(double value);
    partial void OnAccuracy_stdChanged();
    partial void OnPrecision_mediaChanging(double value);
    partial void OnPrecision_mediaChanged();
    partial void OnPrecision_stdChanging(double value);
    partial void OnPrecision_stdChanged();
    partial void OnRecall_medioChanging(double value);
    partial void OnRecall_medioChanged();
    partial void OnRecall_stdChanging(System.Nullable<double> value);
    partial void OnRecall_stdChanged();
    partial void OnAVC_mediaChanging(double value);
    partial void OnAVC_mediaChanged();
    partial void OnAVC_stdChanging(double value);
    partial void OnAVC_stdChanged();
    partial void OnFechaLanzamientoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaLanzamientoChanged();
    partial void OnFechaFinalizacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaFinalizacionChanged();
    partial void OnDuracionChanging(System.Nullable<System.DateTime> value);
    partial void OnDuracionChanged();
    partial void OnAccuracyxgenesChanging(string value);
    partial void OnAccuracyxgenesChanged();
    partial void OnMedianaChanging(double value);
    partial void OnMedianaChanged();
    #endregion
		
		public Resultados()
		{
			this._Simulacion = default(EntityRef<Simulacion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdResultado", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid IdResultado
		{
			get
			{
				return this._IdResultado;
			}
			set
			{
				if ((this._IdResultado != value))
				{
					if (this._Simulacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdResultadoChanging(value);
					this.SendPropertyChanging();
					this._IdResultado = value;
					this.SendPropertyChanged("IdResultado");
					this.OnIdResultadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nummgenes", DbType="Int NOT NULL")]
		public int Nummgenes
		{
			get
			{
				return this._Nummgenes;
			}
			set
			{
				if ((this._Nummgenes != value))
				{
					this.OnNummgenesChanging(value);
					this.SendPropertyChanging();
					this._Nummgenes = value;
					this.SendPropertyChanged("Nummgenes");
					this.OnNummgenesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombregenes", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Nombregenes
		{
			get
			{
				return this._Nombregenes;
			}
			set
			{
				if ((this._Nombregenes != value))
				{
					this.OnNombregenesChanging(value);
					this.SendPropertyChanging();
					this._Nombregenes = value;
					this.SendPropertyChanged("Nombregenes");
					this.OnNombregenesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idgenes", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Idgenes
		{
			get
			{
				return this._Idgenes;
			}
			set
			{
				if ((this._Idgenes != value))
				{
					this.OnIdgenesChanging(value);
					this.SendPropertyChanging();
					this._Idgenes = value;
					this.SendPropertyChanged("Idgenes");
					this.OnIdgenesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accuracy_media", DbType="Float NOT NULL")]
		public double Accuracy_media
		{
			get
			{
				return this._Accuracy_media;
			}
			set
			{
				if ((this._Accuracy_media != value))
				{
					this.OnAccuracy_mediaChanging(value);
					this.SendPropertyChanging();
					this._Accuracy_media = value;
					this.SendPropertyChanged("Accuracy_media");
					this.OnAccuracy_mediaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accuracy_std", DbType="Float NOT NULL")]
		public double Accuracy_std
		{
			get
			{
				return this._Accuracy_std;
			}
			set
			{
				if ((this._Accuracy_std != value))
				{
					this.OnAccuracy_stdChanging(value);
					this.SendPropertyChanging();
					this._Accuracy_std = value;
					this.SendPropertyChanged("Accuracy_std");
					this.OnAccuracy_stdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precision_media", DbType="Float NOT NULL")]
		public double Precision_media
		{
			get
			{
				return this._Precision_media;
			}
			set
			{
				if ((this._Precision_media != value))
				{
					this.OnPrecision_mediaChanging(value);
					this.SendPropertyChanging();
					this._Precision_media = value;
					this.SendPropertyChanged("Precision_media");
					this.OnPrecision_mediaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precision_std", DbType="Float NOT NULL")]
		public double Precision_std
		{
			get
			{
				return this._Precision_std;
			}
			set
			{
				if ((this._Precision_std != value))
				{
					this.OnPrecision_stdChanging(value);
					this.SendPropertyChanging();
					this._Precision_std = value;
					this.SendPropertyChanged("Precision_std");
					this.OnPrecision_stdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recall_medio", DbType="Float NOT NULL")]
		public double Recall_medio
		{
			get
			{
				return this._Recall_medio;
			}
			set
			{
				if ((this._Recall_medio != value))
				{
					this.OnRecall_medioChanging(value);
					this.SendPropertyChanging();
					this._Recall_medio = value;
					this.SendPropertyChanged("Recall_medio");
					this.OnRecall_medioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recall_std", DbType="Float")]
		public System.Nullable<double> Recall_std
		{
			get
			{
				return this._Recall_std;
			}
			set
			{
				if ((this._Recall_std != value))
				{
					this.OnRecall_stdChanging(value);
					this.SendPropertyChanging();
					this._Recall_std = value;
					this.SendPropertyChanged("Recall_std");
					this.OnRecall_stdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVC_media", DbType="Float NOT NULL")]
		public double AVC_media
		{
			get
			{
				return this._AVC_media;
			}
			set
			{
				if ((this._AVC_media != value))
				{
					this.OnAVC_mediaChanging(value);
					this.SendPropertyChanging();
					this._AVC_media = value;
					this.SendPropertyChanged("AVC_media");
					this.OnAVC_mediaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVC_std", DbType="Float NOT NULL")]
		public double AVC_std
		{
			get
			{
				return this._AVC_std;
			}
			set
			{
				if ((this._AVC_std != value))
				{
					this.OnAVC_stdChanging(value);
					this.SendPropertyChanging();
					this._AVC_std = value;
					this.SendPropertyChanged("AVC_std");
					this.OnAVC_stdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaLanzamiento", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaLanzamiento
		{
			get
			{
				return this._FechaLanzamiento;
			}
			set
			{
				if ((this._FechaLanzamiento != value))
				{
					this.OnFechaLanzamientoChanging(value);
					this.SendPropertyChanging();
					this._FechaLanzamiento = value;
					this.SendPropertyChanged("FechaLanzamiento");
					this.OnFechaLanzamientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFinalizacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaFinalizacion
		{
			get
			{
				return this._FechaFinalizacion;
			}
			set
			{
				if ((this._FechaFinalizacion != value))
				{
					this.OnFechaFinalizacionChanging(value);
					this.SendPropertyChanging();
					this._FechaFinalizacion = value;
					this.SendPropertyChanged("FechaFinalizacion");
					this.OnFechaFinalizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duracion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Duracion
		{
			get
			{
				return this._Duracion;
			}
			set
			{
				if ((this._Duracion != value))
				{
					this.OnDuracionChanging(value);
					this.SendPropertyChanging();
					this._Duracion = value;
					this.SendPropertyChanged("Duracion");
					this.OnDuracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accuracyxgenes", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Accuracyxgenes
		{
			get
			{
				return this._Accuracyxgenes;
			}
			set
			{
				if ((this._Accuracyxgenes != value))
				{
					this.OnAccuracyxgenesChanging(value);
					this.SendPropertyChanging();
					this._Accuracyxgenes = value;
					this.SendPropertyChanged("Accuracyxgenes");
					this.OnAccuracyxgenesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mediana", DbType="Float NOT NULL")]
		public double Mediana
		{
			get
			{
				return this._Mediana;
			}
			set
			{
				if ((this._Mediana != value))
				{
					this.OnMedianaChanging(value);
					this.SendPropertyChanging();
					this._Mediana = value;
					this.SendPropertyChanged("Mediana");
					this.OnMedianaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Simulacion_Resultados", Storage="_Simulacion", ThisKey="IdResultado", OtherKey="idSimulacion", IsForeignKey=true)]
		public Simulacion Simulacion
		{
			get
			{
				return this._Simulacion.Entity;
			}
			set
			{
				Simulacion previousValue = this._Simulacion.Entity;
				if (((previousValue != value) 
							|| (this._Simulacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Simulacion.Entity = null;
						previousValue.Resultados = null;
					}
					this._Simulacion.Entity = value;
					if ((value != null))
					{
						value.Resultados = this;
						this._IdResultado = value.idSimulacion;
					}
					else
					{
						this._IdResultado = default(System.Guid);
					}
					this.SendPropertyChanged("Simulacion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
